apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-claim
spec:
  storageClassName: ""
  volumeName: gogs-web 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
