apiVersion: v1
kind: Service
metadata:
  name: rappi-demo-sockets
  labels:
    app: rappi-demo-sockets
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 1338
      targetPort: 1338
  selector:
    app: rappi-demo-sockets
