apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rethinkdb-claim
spec:
  storageClassName: ""
  volumeName: rethinkdb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi