apiVersion: v1
kind: Service
metadata:
  name: real-time-db
  labels:
    app: rethinkdb-sts
spec:
  ports:
    - port: 28015
      name: http
    - port: 29015
      name: cluster
  selector:
    app: rethinkdb-sts