apiVersion: apps/v1
kind: Deployment
metadata:
  name: rappi-demo-chat-app
  labels:
    app: rappi-demo-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rappi-demo-chat-app
  template:
    metadata:
      labels:
        app: rappi-demo-chat-app
    spec:
      containers:
        - name: web
          image: 081952199324.dkr.ecr.us-east-1.amazonaws.com/rappi-demo/chat-app:latest
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: awsecr-cred
