apiVersion: v1
kind: Service
metadata:
  name: rappi-demo-chat-app
  labels:
    app: rappi-demo-chat-app
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
  selector:
    app: rappi-demo-chat-app
